name: Update Telegram Messages

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          MARKETAPP_API_TOKEN: ${{ secrets.MARKETAPP_API_TOKEN }}

          USERNAMES_CHAT_ID: ${{ secrets.USERNAMES_CHAT_ID }}
          USERNAMES_MESSAGE_ID: ${{ secrets.USERNAMES_MESSAGE_ID }}

          NUMBERS_CHAT_ID: ${{ secrets.NUMBERS_CHAT_ID }}
          NUMBERS_MESSAGE_ID: ${{ secrets.NUMBERS_MESSAGE_ID }}
          
          PROMO_CHAT_ID: ${{ secrets.PROMO_CHAT_ID }}
          PROMO_MESSAGE_ID: ${{ secrets.PROMO_MESSAGE_ID }}

          USERNAMES_5_URL: "https://marketapp.ws/collection/EQCA14o1-VWhS2efqoh_9M1b_A9DtKTuoqfmkn83AbJzwnPi/?tab=nfts&view=list&filter_by=sale&sort_by=price_asc&market_filter_by=any&attrs=Length%7E5&query="
          USERNAMES_6_URL: "https://marketapp.ws/collection/EQCA14o1-VWhS2efqoh_9M1b_A9DtKTuoqfmkn83AbJzwnPi/?tab=nfts&view=list&filter_by=sale&sort_by=price_asc&market_filter_by=any&attrs=Length%7E6&query="
          USERNAMES_7_URL: "https://marketapp.ws/collection/EQCA14o1-VWhS2efqoh_9M1b_A9DtKTuoqfmkn83AbJzwnPi/?tab=nfts&view=list&filter_by=sale&sort_by=price_asc&market_filter_by=any&attrs=Length%7E7&query="
          
          NUMBERS_COLLECTION_ADDRESS: "https://marketapp.ws/collection/EQAOQdwdw8kGftJCSFgOErM1mBjYPe4DBPq8-AhF6vr9si5N/"

          TZ: "Asia/Shanghai"
          MAX_PAGES: "100"
          MAX_QUERY_PAGES: "2"

        run: python bot.py
